/**
 * generate-css.js
 *
 * Reads tokens.json and produces:
 *   1. tokens.css        — CSS custom properties inside :root { … }
 *   2. tailwind-tokens.js — CommonJS module for Tailwind theme.extend
 *
 * Usage:  node generate-css.js
 * Requires: Node.js built-in modules only (fs, path)
 */

const fs = require("fs");
const path = require("path");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a camelCase string to kebab-case.
 *   "sidebarWidth"  → "sidebar-width"
 *   "fontFamily"    → "font-family"
 *   "contentMaxWidth" → "content-max-width"
 */
function camelToKebab(str) {
  return str.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/**
 * Recursively flatten a nested object into CSS custom-property entries.
 *
 * @param {object} obj       The current object node
 * @param {string} prefix    The accumulated CSS variable prefix so far
 * @param {Array}  result    Accumulator — mutated in place
 * @returns {Array<{name: string, value: string}>}
 */
function flattenTokens(obj, prefix, result = []) {
  for (const [key, value] of Object.entries(obj)) {
    // Skip JSON-schema meta keys
    if (key.startsWith("$")) continue;

    const kebabKey = camelToKebab(key);
    const varName = prefix ? `${prefix}-${kebabKey}` : `--${kebabKey}`;

    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      flattenTokens(value, varName, result);
    } else {
      result.push({ name: varName, value: String(value) });
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// CSS generation
// ---------------------------------------------------------------------------

function generateCSS(tokens) {
  const entries = flattenTokens(tokens, "");

  const lines = [
    "/**",
    " * tokens.css — Auto-generated CSS custom properties",
    " *",
    " * Source : tokens.json",
    " * Script : generate-css.js",
    ` * Generated : ${new Date().toISOString()}`,
    " *",
    " * DO NOT EDIT THIS FILE BY HAND.",
    " * Re-run `node generate-css.js` after changing tokens.json.",
    " */",
    "",
    ":root {",
  ];

  let currentCategory = null;

  for (const entry of entries) {
    // Derive category from the first segment after "--"
    // e.g. "--color-primary-50" → "color"
    const category = entry.name.replace(/^--/, "").split("-")[0];
    if (category !== currentCategory) {
      if (currentCategory !== null) lines.push("");
      lines.push(`  /* ${category} */`);
      currentCategory = category;
    }
    lines.push(`  ${entry.name}: ${entry.value};`);
  }

  lines.push("}");
  lines.push("");

  return { css: lines.join("\n"), count: entries.length };
}

// ---------------------------------------------------------------------------
// Tailwind tokens generation
// ---------------------------------------------------------------------------

/**
 * Build a nested object from the flat token entries that is ergonomic for
 * Tailwind's theme.extend.  We group by top-level category and map to the
 * Tailwind config key names.
 */
function generateTailwindTokens(tokens) {
  const tw = {};

  // --- colors -----------------------------------------------------------
  // Tailwind expects:  colors: { primary: { 50: '#…', … }, … }
  if (tokens.color) {
    tw.colors = {};
    for (const [group, val] of Object.entries(tokens.color)) {
      if (val !== null && typeof val === "object") {
        tw.colors[group] = {};
        for (const [k, v] of Object.entries(val)) {
          if (v !== null && typeof v === "object") {
            // nested semantic colors  e.g. semantic.success.500
            tw.colors[`${group}-${k}`] = { ...v };
          } else {
            tw.colors[group][k] = v;
          }
        }
        // If the group object is now empty (all children were nested), delete it
        if (Object.keys(tw.colors[group]).length === 0) {
          delete tw.colors[group];
        }
      }
    }
  }

  // --- typography -------------------------------------------------------
  if (tokens.typography) {
    if (tokens.typography.fontFamily) {
      tw.fontFamily = {};
      for (const [k, v] of Object.entries(tokens.typography.fontFamily)) {
        // Tailwind expects arrays for fontFamily
        tw.fontFamily[k] = v.split(",").map((s) => s.trim());
      }
    }
    if (tokens.typography.fontSize) {
      tw.fontSize = { ...tokens.typography.fontSize };
    }
    if (tokens.typography.fontWeight) {
      tw.fontWeight = {};
      for (const [k, v] of Object.entries(tokens.typography.fontWeight)) {
        tw.fontWeight[k] = String(v);
      }
    }
    if (tokens.typography.lineHeight) {
      tw.lineHeight = {};
      for (const [k, v] of Object.entries(tokens.typography.lineHeight)) {
        tw.lineHeight[k] = String(v);
      }
    }
    if (tokens.typography.letterSpacing) {
      tw.letterSpacing = { ...tokens.typography.letterSpacing };
    }
  }

  // --- spacing ----------------------------------------------------------
  if (tokens.spacing) {
    tw.spacing = { ...tokens.spacing };
  }

  // --- borderRadius -----------------------------------------------------
  if (tokens.borderRadius) {
    tw.borderRadius = { ...tokens.borderRadius };
  }

  // --- boxShadow --------------------------------------------------------
  if (tokens.shadow) {
    tw.boxShadow = { ...tokens.shadow };
  }

  // --- zIndex -----------------------------------------------------------
  if (tokens.zIndex) {
    tw.zIndex = {};
    for (const [k, v] of Object.entries(tokens.zIndex)) {
      tw.zIndex[k] = String(v);
    }
  }

  // --- screens (breakpoints) --------------------------------------------
  if (tokens.breakpoint) {
    tw.screens = { ...tokens.breakpoint };
  }

  // --- transition -------------------------------------------------------
  if (tokens.transition) {
    tw.transitionTimingFunction = {};
    tw.transitionDuration = {};
    for (const [k, v] of Object.entries(tokens.transition)) {
      // Parse "200ms ease" → duration "200ms", easing "ease"
      const match = String(v).match(/^(\d+ms)\s+(.+)$/);
      if (match) {
        tw.transitionDuration[k] = match[1];
        tw.transitionTimingFunction[k] = match[2];
      } else {
        tw.transitionDuration[k] = v;
      }
    }
  }

  // --- layout (custom, no direct Tailwind key — expose as-is) -----------
  if (tokens.layout) {
    tw.layout = {};
    for (const [k, v] of Object.entries(tokens.layout)) {
      tw.layout[camelToKebab(k)] = v;
    }
  }

  return tw;
}

function serializeTailwindModule(twTokens) {
  const lines = [
    "/**",
    " * tailwind-tokens.js — Auto-generated Tailwind theme.extend tokens",
    " *",
    " * Source : tokens.json",
    " * Script : generate-css.js",
    ` * Generated : ${new Date().toISOString()}`,
    " *",
    " * Usage in tailwind.config.js:",
    " *",
    ' *   const tokens = require("./design-tokens/tailwind-tokens");',
    " *   module.exports = {",
    " *     theme: {",
    " *       extend: {",
    " *         ...tokens,",
    " *       },",
    " *     },",
    " *   };",
    " *",
    " * DO NOT EDIT THIS FILE BY HAND.",
    " * Re-run `node generate-css.js` after changing tokens.json.",
    " */",
    "",
    `module.exports = ${JSON.stringify(twTokens, null, 2)};`,
    "",
  ];
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const dir = __dirname;
  const tokensPath = path.join(dir, "tokens.json");
  const cssPath = path.join(dir, "tokens.css");
  const twPath = path.join(dir, "tailwind-tokens.js");

  // 1. Read tokens.json
  let raw;
  try {
    raw = fs.readFileSync(tokensPath, "utf-8");
  } catch (err) {
    console.error(`[error] Could not read ${tokensPath}`);
    console.error(`        ${err.message}`);
    process.exit(1);
  }

  let tokens;
  try {
    tokens = JSON.parse(raw);
  } catch (err) {
    console.error(`[error] Invalid JSON in ${tokensPath}`);
    console.error(`        ${err.message}`);
    process.exit(1);
  }

  // 2. Generate tokens.css
  const { css, count } = generateCSS(tokens);
  try {
    fs.writeFileSync(cssPath, css, "utf-8");
    console.log(`[ok] ${cssPath}`);
    console.log(`     ${count} CSS custom properties generated`);
  } catch (err) {
    console.error(`[error] Could not write ${cssPath}`);
    console.error(`        ${err.message}`);
    process.exit(1);
  }

  // 3. Generate tailwind-tokens.js
  const twTokens = generateTailwindTokens(tokens);
  const twSource = serializeTailwindModule(twTokens);
  const twKeyCount = Object.keys(twTokens).reduce((sum, key) => {
    const val = twTokens[key];
    if (val !== null && typeof val === "object") {
      // Count leaf keys recursively
      return sum + countLeaves(val);
    }
    return sum + 1;
  }, 0);

  try {
    fs.writeFileSync(twPath, twSource, "utf-8");
    console.log(`[ok] ${twPath}`);
    console.log(`     ${twKeyCount} Tailwind token entries generated`);
  } catch (err) {
    console.error(`[error] Could not write ${twPath}`);
    console.error(`        ${err.message}`);
    process.exit(1);
  }

  console.log("\nDone.");
}

/** Recursively count leaf (non-object) values in an object tree. */
function countLeaves(obj) {
  let n = 0;
  for (const v of Object.values(obj)) {
    if (v !== null && typeof v === "object" && !Array.isArray(v)) {
      n += countLeaves(v);
    } else {
      n += 1;
    }
  }
  return n;
}

main();
