import { useEffect, useRef, useState } from "react";
import { RefreshCw, ArrowRight } from "lucide-react";
import { Button } from "@/components/atoms/button";
import { PageHeader } from "@/components/molecules/PageHeader";
import { TRACKERS_COPY } from "@/content/trackers";
import type { PromptDto } from "@/types/api";
import {
  usePrompts,
  useGeneratePrompts,
  useConfirmPrompts,
  useRemovePrompt,
  useAddCustomPrompt,
  useUpdatePrompt,
} from "../hooks/usePrompts";
import { PromptLensGroup } from "./PromptLensGroup";
import { TrackerScheduleScreen } from "./TrackerScheduleScreen";

interface PromptReviewScreenProps {
  trackerId: string;
}

export function PromptReviewScreen({ trackerId }: PromptReviewScreenProps) {
  const prompts = usePrompts(trackerId);
  const generate = useGeneratePrompts();
  const confirm = useConfirmPrompts(trackerId);
  const removePrompt = useRemovePrompt(trackerId);
  const addPrompt = useAddCustomPrompt(trackerId);
  const updatePrompt = useUpdatePrompt(trackerId);

  const [confirmed, setConfirmed] = useState(false);
  // Which slice is regenerating: null | "all" | a Visibility Lens id (drives the spinner only).
  const [regenScope, setRegenScope] = useState<string | null>(null);
  const autoGenerated = useRef(false);

  // Fresh tracker (no prompts yet) → generate once on first load.
  useEffect(() => {
    if (
      !autoGenerated.current &&
      prompts.isSuccess &&
      prompts.data.count === 0 &&
      !generate.isPending
    ) {
      autoGenerated.current = true;
      generate.mutate({ trackerId });
    }
  }, [prompts.isSuccess, prompts.data, generate, trackerId]);

  function regenerate(scope: string, vars: { trackerId: string; visibilityLensId?: string }) {
    setRegenScope(scope);
    generate.mutate(vars, { onSettled: () => setRegenScope(null) });
  }

  if (confirmed) {
    return <TrackerScheduleScreen trackerId={trackerId} />;
  }

  // Full-screen spinner only on the very first generation (initial load / empty tracker),
  // never for a regenerate of an already-populated tracker.
  const firstGeneration = generate.isPending && (prompts.data?.count ?? 0) === 0;
  if (prompts.isLoading || firstGeneration) {
    return (
      <div className="flex min-h-[400px] flex-col items-center justify-center gap-3 p-4 text-center">
        <RefreshCw className="h-6 w-6 animate-spin text-primary-600" />
        <p className="text-sm text-neutral-500">{TRACKERS_COPY.review.generating}</p>
      </div>
    );
  }

  if (!prompts.data) return null;
  const data = prompts.data;
  const remaining = Math.max(0, data.promptAllocation - data.count);
  const isFull = remaining === 0;
  const pct =
    data.promptAllocation > 0
      ? Math.min(100, Math.round((data.count / data.promptAllocation) * 100))
      : 0;

  const groups = new Map<string, PromptDto[]>();
  for (const prompt of data.prompts) {
    const group = groups.get(prompt.visibilityLensName) ?? [];
    group.push(prompt);
    groups.set(prompt.visibilityLensName, group);
  }
  // Stable section order by Visibility Lens (coverage order), not by prompt timestamp.
  const checkOrder = new Map(data.checks.map((c, i) => [c.name, i]));
  const orderedGroups = [...groups.entries()].sort(
    ([a], [b]) =>
      (checkOrder.get(a) ?? Number.MAX_SAFE_INTEGER) -
      (checkOrder.get(b) ?? Number.MAX_SAFE_INTEGER),
  );

  function handleConfirm() {
    confirm.mutate(undefined, { onSuccess: () => setConfirmed(true) });
  }

  return (
    <div className="mx-auto max-w-2xl p-4">
      <PageHeader
        title={TRACKERS_COPY.review.title}
        description={TRACKERS_COPY.review.description}
      />

      <div className="mt-3">
        <div className="mb-1 flex items-center justify-between text-xs text-neutral-500">
          <span className="tabular-nums">
            {TRACKERS_COPY.review.allocation
              .replace("{count}", String(data.count))
              .replace("{allocation}", String(data.promptAllocation))}
          </span>
          <span className="tabular-nums">
            {TRACKERS_COPY.review.remaining.replace("{remaining}", String(remaining))}
          </span>
        </div>
        <div className="h-1.5 w-full overflow-hidden rounded-full bg-neutral-100">
          <div
            className="h-full rounded-full bg-primary-500 transition-all"
            style={{ width: `${pct}%` }}
          />
        </div>
        {isFull && <p className="mt-1 text-xs text-neutral-400">{TRACKERS_COPY.review.full}</p>}
      </div>

      {data.count === 0 ? (
        <div className="mt-6 rounded-lg border border-dashed border-neutral-300 p-10 text-center">
          <p className="text-sm text-neutral-500">{TRACKERS_COPY.review.empty}</p>
          <Button className="mt-4" onClick={() => regenerate("all", { trackerId })}>
            {TRACKERS_COPY.review.generate}
          </Button>
        </div>
      ) : (
        <div className="mt-5 space-y-3">
          {orderedGroups.map(([checkName, items]) => (
            <PromptLensGroup
              key={checkName}
              title={checkName}
              prompts={items}
              topics={data.topics}
              canAdd={!isFull}
              isRegenerating={regenScope === items[0].visibilityLensId}
              reviewReason={items[0].reviewReason ?? undefined}
              onRegenerate={() =>
                regenerate(items[0].visibilityLensId, {
                  trackerId,
                  visibilityLensId: items[0].visibilityLensId,
                })
              }
              onRemove={(promptId) => removePrompt.mutate(promptId)}
              onEdit={(promptId, text) => updatePrompt.mutate({ promptId, text })}
              onAdd={(text, topicId) =>
                addPrompt.mutate({
                  text,
                  visibilityLensId: items[0].visibilityLensId,
                  primaryTopicId: topicId,
                })
              }
            />
          ))}

          <Button
            onClick={handleConfirm}
            disabled={confirm.isPending}
            className="w-full gap-2"
            size="lg"
          >
            {confirm.isPending ? TRACKERS_COPY.review.confirming : TRACKERS_COPY.review.confirm}
            {!confirm.isPending && <ArrowRight className="h-4 w-4" />}
          </Button>
        </div>
      )}
    </div>
  );
}
