import { useEffect, useRef, useState } from "react";
import {
  RefreshCw,
  Check,
  X,
  ArrowRight,
  Plus,
  Sparkles,
  User,
  Compass,
  ShoppingCart,
  Swords,
  Heart,
  Quote,
  FileSearch,
  Eye,
  type LucideIcon,
} from "lucide-react";
import { Button } from "@/components/atoms/button";
import { Badge } from "@/components/atoms/badge";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/atoms/card";
import { Input } from "@/components/atoms/input";
import { InlineEdit } from "@/components/atoms/inline-edit";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "@/components/atoms/select";
import { PageHeader } from "@/components/molecules/PageHeader";
import { TRACKERS_COPY } from "@/content/trackers";
import type { PromptDto } from "@/types/api";
import {
  usePrompts,
  useGeneratePrompts,
  useConfirmPrompts,
  useRemovePrompt,
  useAddCustomPrompt,
  useUpdatePrompt,
} from "../hooks/usePrompts";

const CHECK_ICONS: Record<string, LucideIcon> = {
  Discovery: Compass,
  "Buying Intent": ShoppingCart,
  "Competitor Comparison": Swords,
  "Sentiment & Trust": Heart,
  "Citation Visibility": Quote,
  "Content Gaps": FileSearch,
};

interface PromptReviewScreenProps {
  trackerId: string;
}

export function PromptReviewScreen({ trackerId }: PromptReviewScreenProps) {
  const prompts = usePrompts(trackerId);
  const generate = useGeneratePrompts();
  const confirm = useConfirmPrompts(trackerId);
  const removePrompt = useRemovePrompt(trackerId);
  const addPrompt = useAddCustomPrompt(trackerId);
  const updatePrompt = useUpdatePrompt(trackerId);

  const [confirmedCount, setConfirmedCount] = useState<number | null>(null);
  const [adding, setAdding] = useState(false);
  const [draftText, setDraftText] = useState("");
  const [draftCheck, setDraftCheck] = useState("");
  const [draftTopic, setDraftTopic] = useState("");
  const autoGenerated = useRef(false);

  // Fresh tracker (no prompts yet) → generate once on first load.
  useEffect(() => {
    if (
      !autoGenerated.current &&
      prompts.isSuccess &&
      prompts.data.count === 0 &&
      !generate.isPending
    ) {
      autoGenerated.current = true;
      generate.mutate({ trackerId });
    }
  }, [prompts.isSuccess, prompts.data, generate, trackerId]);

  if (confirmedCount !== null) {
    return (
      <div className="flex min-h-[400px] items-center justify-center p-4">
        <Card className="w-full max-w-md text-center">
          <CardHeader>
            <div className="mx-auto mb-2 flex h-12 w-12 items-center justify-center rounded-full bg-semantic-success-100 text-semantic-success-600">
              <Check className="h-6 w-6" />
            </div>
            <CardTitle>{TRACKERS_COPY.review.confirmedTitle}</CardTitle>
            <CardDescription>
              {TRACKERS_COPY.review.confirmedDescription.replace("{count}", String(confirmedCount))}
            </CardDescription>
          </CardHeader>
        </Card>
      </div>
    );
  }

  if (prompts.isLoading || generate.isPending) {
    return (
      <div className="flex min-h-[400px] flex-col items-center justify-center gap-3 p-4 text-center">
        <RefreshCw className="h-6 w-6 animate-spin text-primary-600" />
        <p className="text-sm text-neutral-500">{TRACKERS_COPY.review.generating}</p>
      </div>
    );
  }

  if (!prompts.data) return null;
  const data = prompts.data;
  const remaining = Math.max(0, data.promptAllocation - data.count);
  const isFull = remaining === 0;
  const pct =
    data.promptAllocation > 0
      ? Math.min(100, Math.round((data.count / data.promptAllocation) * 100))
      : 0;

  const groups = new Map<string, PromptDto[]>();
  for (const prompt of data.prompts) {
    const group = groups.get(prompt.visibilityCheckName) ?? [];
    group.push(prompt);
    groups.set(prompt.visibilityCheckName, group);
  }

  function handleAdd(e: React.FormEvent) {
    e.preventDefault();
    const text = draftText.trim();
    if (!text || !draftCheck) return;
    addPrompt.mutate(
      { text, visibilityCheckId: draftCheck, primaryTopicId: draftTopic || null },
      {
        onSuccess: () => {
          setDraftText("");
          setDraftCheck("");
          setDraftTopic("");
          setAdding(false);
        },
      },
    );
  }

  function handleConfirm() {
    confirm.mutate(undefined, { onSuccess: (res) => setConfirmedCount(res.activatedCount) });
  }

  return (
    <div className="mx-auto max-w-2xl p-4">
      <PageHeader title={TRACKERS_COPY.review.title} description={TRACKERS_COPY.review.description}>
        <Button
          variant="outline"
          size="sm"
          className="gap-1.5"
          disabled={generate.isPending}
          onClick={() => generate.mutate({ trackerId })}
        >
          <RefreshCw className="h-3.5 w-3.5" />
          {TRACKERS_COPY.review.regenerate}
        </Button>
      </PageHeader>

      <div className="mt-3">
        <div className="mb-1 flex items-center justify-between text-xs text-neutral-500">
          <span className="tabular-nums">
            {TRACKERS_COPY.review.allocation
              .replace("{count}", String(data.count))
              .replace("{allocation}", String(data.promptAllocation))}
          </span>
          <span className="tabular-nums">
            {TRACKERS_COPY.review.remaining.replace("{remaining}", String(remaining))}
          </span>
        </div>
        <div className="h-1.5 w-full overflow-hidden rounded-full bg-neutral-100">
          <div
            className="h-full rounded-full bg-primary-500 transition-all"
            style={{ width: `${pct}%` }}
          />
        </div>
      </div>

      {data.count === 0 ? (
        <div className="mt-6 rounded-lg border border-dashed border-neutral-300 p-10 text-center">
          <p className="text-sm text-neutral-500">{TRACKERS_COPY.review.empty}</p>
          <Button className="mt-4" onClick={() => generate.mutate({ trackerId })}>
            {TRACKERS_COPY.review.generate}
          </Button>
        </div>
      ) : (
        <div className="mt-5 space-y-5">
          {[...groups.entries()].map(([checkName, items]) => {
            const Icon = CHECK_ICONS[checkName] ?? Eye;
            return (
              <div key={checkName}>
                <div className="mb-2 flex items-center gap-2 text-[11px] font-medium uppercase tracking-wide text-neutral-400">
                  <Icon className="h-3.5 w-3.5" />
                  <span>{checkName}</span>
                  <span className="tabular-nums text-neutral-300">{items.length}</span>
                  <button
                    type="button"
                    onClick={() =>
                      generate.mutate({ trackerId, visibilityCheckId: items[0].visibilityCheckId })
                    }
                    aria-label={TRACKERS_COPY.review.regenerateCheck.replace("{check}", checkName)}
                    className="ml-auto rounded p-1 text-neutral-400 transition-colors hover:bg-neutral-100 hover:text-neutral-600"
                  >
                    <RefreshCw className="h-3.5 w-3.5" />
                  </button>
                </div>
                <ul className="space-y-1.5">
                  {items.map((prompt) => {
                    const isAi = prompt.source !== "UserAdded";
                    return (
                      <li
                        key={prompt.id}
                        className="group flex items-start gap-2 rounded-lg border border-neutral-200 bg-surface-card p-2 transition-all hover:border-neutral-300 hover:shadow-sm"
                      >
                        <span
                          className="mt-1.5 shrink-0 text-neutral-400"
                          aria-label={
                            isAi ? TRACKERS_COPY.review.sourceAi : TRACKERS_COPY.review.sourceHuman
                          }
                          title={
                            isAi ? TRACKERS_COPY.review.sourceAi : TRACKERS_COPY.review.sourceHuman
                          }
                        >
                          {isAi ? <Sparkles className="h-4 w-4" /> : <User className="h-4 w-4" />}
                        </span>
                        <div className="min-w-0 flex-1">
                          <InlineEdit
                            value={prompt.text}
                            onChange={(text) => updatePrompt.mutate({ promptId: prompt.id, text })}
                            placeholder={TRACKERS_COPY.review.editPlaceholder}
                            className="text-neutral-900"
                          />
                          {prompt.primaryTopicName && (
                            <div className="mt-1 pl-2">
                              <Badge variant="secondary">{prompt.primaryTopicName}</Badge>
                            </div>
                          )}
                        </div>
                        <button
                          type="button"
                          onClick={() => removePrompt.mutate(prompt.id)}
                          aria-label={`Remove prompt: ${prompt.text}`}
                          className="mt-1.5 shrink-0 rounded-md p-1 text-neutral-400 opacity-0 transition-all hover:bg-neutral-100 hover:text-neutral-600 focus-visible:opacity-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-neutral-300 group-hover:opacity-100 pointer-coarse:opacity-100"
                        >
                          <X className="h-4 w-4" />
                        </button>
                      </li>
                    );
                  })}
                </ul>
              </div>
            );
          })}

          <div>
            {isFull ? (
              <p className="text-xs text-neutral-400">{TRACKERS_COPY.review.full}</p>
            ) : adding ? (
              <form
                onSubmit={handleAdd}
                className="space-y-2 rounded-lg border border-neutral-200 p-3"
              >
                <Input
                  value={draftText}
                  onChange={(e) => setDraftText(e.target.value)}
                  placeholder={TRACKERS_COPY.review.addPlaceholder}
                  autoFocus
                />
                <div className="flex flex-wrap items-center gap-2">
                  <Select value={draftCheck} onValueChange={setDraftCheck}>
                    <SelectTrigger selectSize="sm" className="min-w-[10rem]">
                      <SelectValue placeholder={TRACKERS_COPY.review.checkPlaceholder} />
                    </SelectTrigger>
                    <SelectContent>
                      {data.checks.map((c) => (
                        <SelectItem key={c.id} value={c.id}>
                          {c.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <Select value={draftTopic} onValueChange={setDraftTopic}>
                    <SelectTrigger selectSize="sm" className="min-w-[10rem]">
                      <SelectValue placeholder={TRACKERS_COPY.review.topicPlaceholder} />
                    </SelectTrigger>
                    <SelectContent>
                      {data.topics.map((t) => (
                        <SelectItem key={t.id} value={t.id}>
                          {t.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <Button
                    type="submit"
                    size="sm"
                    disabled={!draftText.trim() || !draftCheck || addPrompt.isPending}
                  >
                    {TRACKERS_COPY.review.add}
                  </Button>
                  <Button type="button" variant="ghost" size="sm" onClick={() => setAdding(false)}>
                    {TRACKERS_COPY.review.cancel}
                  </Button>
                </div>
              </form>
            ) : (
              <Button variant="ghost" size="sm" className="gap-1" onClick={() => setAdding(true)}>
                <Plus className="h-3.5 w-3.5" />
                {TRACKERS_COPY.review.addCustom}
              </Button>
            )}
          </div>

          <Button
            onClick={handleConfirm}
            disabled={confirm.isPending}
            className="w-full gap-2"
            size="lg"
          >
            {confirm.isPending ? TRACKERS_COPY.review.confirming : TRACKERS_COPY.review.confirm}
            {!confirm.isPending && <ArrowRight className="h-4 w-4" />}
          </Button>
        </div>
      )}
    </div>
  );
}
