// <auto-generated />
using System;
using AIVisibility.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIVisibility.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525131203_TrimTopicColumns")]
    partial class TrimTopicColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIVisibility.Domain.Entities.AIAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PromptRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_run_id");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.HasKey("Id");

                    b.HasIndex("PromptRunId")
                        .IsUnique();

                    b.ToTable("ai_answers", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.AIPlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDefaultSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default_selected");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ai_platforms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Code = "ChatGpt",
                            DisplayOrder = 1,
                            IsDefaultSelected = true,
                            Name = "ChatGPT"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Code = "ChatGptSearch",
                            DisplayOrder = 2,
                            IsDefaultSelected = false,
                            Name = "ChatGPT Search"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Code = "Gemini",
                            DisplayOrder = 3,
                            IsDefaultSelected = false,
                            Name = "Gemini"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Code = "Claude",
                            DisplayOrder = 4,
                            IsDefaultSelected = false,
                            Name = "Claude"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Code = "Grok",
                            DisplayOrder = 5,
                            IsDefaultSelected = false,
                            Name = "Grok"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Code = "Perplexity",
                            DisplayOrder = 6,
                            IsDefaultSelected = false,
                            Name = "Perplexity"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Code = "Copilot",
                            DisplayOrder = 7,
                            IsDefaultSelected = false,
                            Name = "Copilot"
                        });
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Audience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DiscoveryRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("discovery_run_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DiscoveryRunId");

                    b.ToTable("audiences", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("aliases");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website_url");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.BrandProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Industry")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("industry");

                    b.Property<string>("Positioning")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("positioning");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("short_description");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("BrandId")
                        .IsUnique();

                    b.ToTable("brand_profiles", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Competitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DiscoveryRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("discovery_run_id");

                    b.Property<string>("Domain")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("domain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DiscoveryRunId");

                    b.ToTable("competitors", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.CrawledPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DiscoveryRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("discovery_run_id");

                    b.Property<string>("ExtractedTextBlobRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("extracted_text_blob_ref");

                    b.Property<string>("HeadingsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("headings");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("meta_description");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryRunId");

                    b.ToTable("crawled_pages", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.DiscoveryRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<int>("PagesCrawled")
                        .HasColumnType("integer")
                        .HasColumnName("pages_crawled");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("discovery_runs", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<Guid>("DiscoveryRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("discovery_run_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DiscoveryRunId");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DiscoveryRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("discovery_run_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DiscoveryRunId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PrimaryTopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_topic_id");

                    b.Property<Guid?>("PromptTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_template_id");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prompt_text");

                    b.Property<Guid?>("ReplacesPromptId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaces_prompt_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TrackerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracker_configuration_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VisibilityCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("visibility_check_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TrackerConfigurationId");

                    b.ToTable("prompts", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptAudience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AudienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("audience_id");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("prompt_audiences", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptCompetitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_id");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("prompt_competitors", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("prompt_markets", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("prompt_products", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AIPlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_platform_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_run_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("Status");

                    b.ToTable("prompt_runs", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("template_text");

                    b.Property<Guid>("VisibilityCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("visibility_check_id");

                    b.HasKey("Id");

                    b.HasIndex("VisibilityCheckId");

                    b.ToTable("prompt_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000101"),
                            Name = "Category discovery",
                            TemplateText = "What are the best {category} options in {market}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000102"),
                            Name = "Category recommendation",
                            TemplateText = "Which {category} would you recommend in {market}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000103"),
                            Name = "Leading providers",
                            TemplateText = "Who are the leading {category} providers right now?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000201"),
                            Name = "Buying intent",
                            TemplateText = "I want to buy {category} for {topic} — which do you recommend?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000202"),
                            Name = "Budget choice",
                            TemplateText = "What's the best {category} for {topic} on a budget?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000203"),
                            Name = "Ready to choose",
                            TemplateText = "I'm ready to choose a {category} for {topic} — what should I go with?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000301"),
                            Name = "Head to head",
                            TemplateText = "How does {brand} compare to {competitor} for {category}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000302"),
                            Name = "Which is better",
                            TemplateText = "Is {brand} or {competitor} the better {category}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000303"),
                            Name = "Key differences",
                            TemplateText = "What are the main differences between {brand} and {competitor}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000401"),
                            Name = "Reliability",
                            TemplateText = "Is {brand} a reliable {category}? What is its reputation?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000402"),
                            Name = "Reviews",
                            TemplateText = "What do people say about {brand}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000403"),
                            Name = "Trust",
                            TemplateText = "Can I trust {brand} for {category}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000501"),
                            Name = "Authoritative sources",
                            TemplateText = "What are the most authoritative sources about {topic} in {category}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000502"),
                            Name = "Experts to follow",
                            TemplateText = "Which experts or publications should I follow on {topic}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000503"),
                            Name = "Trustworthy info",
                            TemplateText = "Where can I find trustworthy information about {topic}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000601"),
                            Name = "Considerations",
                            TemplateText = "What should I consider about {topic} when choosing a {category}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000602"),
                            Name = "Questions to ask",
                            TemplateText = "What questions should I ask about {topic} before choosing a {category}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000603"),
                            Name = "Overlooked factors",
                            TemplateText = "What do most people overlook about {topic} when it comes to {category}?",
                            VisibilityCheckId = new Guid("c0000000-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("prompt_topics", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_count");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<int>("PlatformCount")
                        .HasColumnType("integer")
                        .HasColumnName("platform_count");

                    b.Property<int>("PromptCount")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_count");

                    b.Property<int>("ScanCheckCount")
                        .HasColumnType("integer")
                        .HasColumnName("scan_check_count");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TrackerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracker_configuration_id");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TrackerConfigurationId");

                    b.ToTable("scan_runs", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<Guid>("DiscoveryRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("discovery_run_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DiscoveryRunId");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerAudience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AudienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("audience_id");

                    b.Property<Guid>("TrackerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracker_configuration_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackerConfigurationId");

                    b.ToTable("tracker_audiences", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerCompetitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitor_id");

                    b.Property<Guid>("TrackerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracker_configuration_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackerConfigurationId");

                    b.ToTable("tracker_competitors", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cadence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsNameUserEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_name_user_edited");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<int>("PromptAllocation")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_allocation");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("tracker_configurations", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<Guid>("TrackerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracker_configuration_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackerConfigurationId");

                    b.ToTable("tracker_markets", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerPlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AIPlatformId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_platform_id");

                    b.Property<Guid>("TrackerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracker_configuration_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackerConfigurationId");

                    b.ToTable("tracker_platforms", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TrackerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracker_configuration_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackerConfigurationId");

                    b.ToTable("tracker_products", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<Guid>("TrackerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracker_configuration_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackerConfigurationId");

                    b.ToTable("tracker_topics", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerVisibilityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TrackerConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tracker_configuration_id");

                    b.Property<Guid>("VisibilityCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("visibility_check_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackerConfigurationId");

                    b.ToTable("tracker_visibility_checks", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrustSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DiscoveryRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("discovery_run_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("signal_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("SourcePagesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_pages");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("DiscoveryRunId");

                    b.ToTable("trust_signals", (string)null);
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.VisibilityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("visibility_checks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Code = "Discovery",
                            Description = "Does the AI surface the brand when asked about the category or topic?",
                            DisplayOrder = 1,
                            Name = "Discovery"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Code = "BuyingIntent",
                            Description = "Is the brand recommended for high-intent, purchase-oriented prompts?",
                            DisplayOrder = 2,
                            Name = "Buying Intent"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Code = "CompetitorComparison",
                            Description = "How does the AI compare the brand against its competitors?",
                            DisplayOrder = 3,
                            Name = "Competitor Comparison"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Code = "SentimentAndTrust",
                            Description = "What sentiment and trust signals does the AI express about the brand?",
                            DisplayOrder = 4,
                            Name = "Sentiment & Trust"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Code = "CitationVisibility",
                            Description = "Is the brand's own content cited as a source in AI answers?",
                            DisplayOrder = 5,
                            Name = "Citation Visibility"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Code = "ContentGaps",
                            Description = "Where is the brand absent from AI answers when it should be present?",
                            DisplayOrder = 6,
                            Name = "Content Gaps"
                        });
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.AIAnswer", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.PromptRun", "PromptRun")
                        .WithOne("Answer")
                        .HasForeignKey("AIVisibility.Domain.Entities.AIAnswer", "PromptRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromptRun");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Audience", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Brand", "Brand")
                        .WithMany("Audiences")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVisibility.Domain.Entities.DiscoveryRun", "DiscoveryRun")
                        .WithMany("Audiences")
                        .HasForeignKey("DiscoveryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("DiscoveryRun");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.BrandProfile", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Brand", "Brand")
                        .WithOne("BrandProfile")
                        .HasForeignKey("AIVisibility.Domain.Entities.BrandProfile", "BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Competitor", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Brand", "Brand")
                        .WithMany("Competitors")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVisibility.Domain.Entities.DiscoveryRun", "DiscoveryRun")
                        .WithMany("Competitors")
                        .HasForeignKey("DiscoveryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("DiscoveryRun");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.CrawledPage", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.DiscoveryRun", "DiscoveryRun")
                        .WithMany("CrawledPages")
                        .HasForeignKey("DiscoveryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscoveryRun");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.DiscoveryRun", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Brand", "Brand")
                        .WithMany("DiscoveryRuns")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Market", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Brand", "Brand")
                        .WithMany("Markets")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVisibility.Domain.Entities.DiscoveryRun", "DiscoveryRun")
                        .WithMany("Markets")
                        .HasForeignKey("DiscoveryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("DiscoveryRun");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Product", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVisibility.Domain.Entities.DiscoveryRun", "DiscoveryRun")
                        .WithMany("Products")
                        .HasForeignKey("DiscoveryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("DiscoveryRun");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Prompt", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.TrackerConfiguration", "TrackerConfiguration")
                        .WithMany()
                        .HasForeignKey("TrackerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackerConfiguration");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptAudience", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Prompt", "Prompt")
                        .WithMany("Audiences")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptCompetitor", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Prompt", "Prompt")
                        .WithMany("Competitors")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptMarket", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Prompt", "Prompt")
                        .WithMany("Markets")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptProduct", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Prompt", "Prompt")
                        .WithMany("Products")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptRun", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.ScanRun", "ScanRun")
                        .WithMany("PromptRuns")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptTopic", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Prompt", "Prompt")
                        .WithMany("Topics")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.ScanRun", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.TrackerConfiguration", "TrackerConfiguration")
                        .WithMany()
                        .HasForeignKey("TrackerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackerConfiguration");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Topic", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Brand", "Brand")
                        .WithMany("Topics")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVisibility.Domain.Entities.DiscoveryRun", "DiscoveryRun")
                        .WithMany("Topics")
                        .HasForeignKey("DiscoveryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("DiscoveryRun");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerAudience", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.TrackerConfiguration", "TrackerConfiguration")
                        .WithMany("Audiences")
                        .HasForeignKey("TrackerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackerConfiguration");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerCompetitor", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.TrackerConfiguration", "TrackerConfiguration")
                        .WithMany("Competitors")
                        .HasForeignKey("TrackerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackerConfiguration");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerConfiguration", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerMarket", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.TrackerConfiguration", "TrackerConfiguration")
                        .WithMany("Markets")
                        .HasForeignKey("TrackerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackerConfiguration");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerPlatform", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.TrackerConfiguration", "TrackerConfiguration")
                        .WithMany()
                        .HasForeignKey("TrackerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackerConfiguration");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerProduct", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.TrackerConfiguration", "TrackerConfiguration")
                        .WithMany("Products")
                        .HasForeignKey("TrackerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackerConfiguration");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerTopic", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.TrackerConfiguration", "TrackerConfiguration")
                        .WithMany("Topics")
                        .HasForeignKey("TrackerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackerConfiguration");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerVisibilityCheck", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.TrackerConfiguration", "TrackerConfiguration")
                        .WithMany("VisibilityChecks")
                        .HasForeignKey("TrackerConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackerConfiguration");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrustSignal", b =>
                {
                    b.HasOne("AIVisibility.Domain.Entities.Brand", "Brand")
                        .WithMany("TrustSignals")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIVisibility.Domain.Entities.DiscoveryRun", "DiscoveryRun")
                        .WithMany("TrustSignals")
                        .HasForeignKey("DiscoveryRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("DiscoveryRun");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Audiences");

                    b.Navigation("BrandProfile");

                    b.Navigation("Competitors");

                    b.Navigation("DiscoveryRuns");

                    b.Navigation("Markets");

                    b.Navigation("Products");

                    b.Navigation("Topics");

                    b.Navigation("TrustSignals");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.DiscoveryRun", b =>
                {
                    b.Navigation("Audiences");

                    b.Navigation("Competitors");

                    b.Navigation("CrawledPages");

                    b.Navigation("Markets");

                    b.Navigation("Products");

                    b.Navigation("Topics");

                    b.Navigation("TrustSignals");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.Prompt", b =>
                {
                    b.Navigation("Audiences");

                    b.Navigation("Competitors");

                    b.Navigation("Markets");

                    b.Navigation("Products");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.PromptRun", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.ScanRun", b =>
                {
                    b.Navigation("PromptRuns");
                });

            modelBuilder.Entity("AIVisibility.Domain.Entities.TrackerConfiguration", b =>
                {
                    b.Navigation("Audiences");

                    b.Navigation("Competitors");

                    b.Navigation("Markets");

                    b.Navigation("Products");

                    b.Navigation("Topics");

                    b.Navigation("VisibilityChecks");
                });
#pragma warning restore 612, 618
        }
    }
}
