export const APP_COPY = {
  name: "Lumina",
  nav: {
    addBrand: "Add Brand",
    brands: "Brands",
    overview: "Overview",
    trackers: "Trackers",
    aiQuestions: "AI Questions",
    lenses: "Lenses",
    lensDiscovery: "Discovery",
    lensBuyingIntent: "Buying Intent",
    lensCompetitive: "Competitive",
    lensSentiment: "Sentiment",
    lensCitations: "Citations",
    lensContentGaps: "Content Gaps",
    recommendations: "Recommendations",
    topics: "Topics",
    sources: "Sources",
    competitors: "Competitors",
    claimsRisks: "Claims & Risks",
    reports: "Reports",
    scanHistory: "Scan History",
    brandDiscovery: "Brand Discovery",
    workspace: "Workspace",
    settingsProfile: "Profile",
  },
  navSections: {
    dashboard: "Dashboard",
    strategy: "Strategy",
    intelligence: "Intelligence",
    reporting: "Reporting",
    setup: "Setup",
  },
  stepper: {
    progressLabel: "Wizard progress",
    next: "Next",
    back: "Back",
    loading: "Loading...",
  },
  error: {
    title: "Something went wrong",
    description: "An unexpected error occurred. Please try again.",
    retry: "Try again",
  },
} as const;
