export const REPORTS_COPY = {
  scanResults: {
    title: "Scan Results",
    subtitle: "{brandName} — {trackerName}",
    sections: {
      summary: "Summary",
      coreMetrics: "Core Metrics",
      sentimentDistribution: "Brand Sentiment Distribution",
      topCitedSources: "Top Cited Sources",
      byPlatform: "By Platform",
      byLens: "By Visibility Lens",
      byTopic: "By Topic",
      byCompetitor: "By Competitor",
    },
    summary: {
      scanStatus: "Scan status",
      analysisStatus: "Analysis status",
      startedAt: "Started",
      completedAt: "Completed",
      checks: "{completed} of {total} checks completed",
      checksWithFailures: "{completed} of {total} checks ({failed} failed)",
      platforms: "Platforms",
    },
    metrics: {
      brandMentionRate: "Brand mention rate",
      brandRecommendationRate: "Recommendation rate",
      brandShareOfVoice: "Share of voice",
      averageBrandRank: "Average brand rank",
      competitorMentionCount: "Competitor mentions",
      productMentionCount: "Product mentions",
      citationCount: "Citations",
      ownedCitationCount: "Owned",
      competitorCitationCount: "Competitor",
      thirdPartyCitationCount: "Third-party",
      unknownCitationCount: "Unknown",
      noData: "No data",
    },
    breakdowns: {
      name: "Name",
      mentionRate: "Mention rate",
      recommendationRate: "Rec. rate",
      shareOfVoice: "SoV",
      citations: "Citations",
      mentionCount: "Mentions",
      recommendationCount: "Recommended",
      noRows: "No data for this dimension yet.",
    },
    empty: {
      notFound:
        "Scan results not found. The scan may not exist or analysis may not have started yet.",
    },
    error: {
      title: "Couldn't load scan results",
      description: "Something went wrong fetching the scan results.",
    },
  },
  scanList: {
    title: "All Scans",
    subtitle:
      "Temporary index of recent scans across all trackers. Click a row to open its results.",
    columns: {
      startedAt: "Started",
      brand: "Brand",
      tracker: "Tracker",
      scanStatus: "Scan",
      analysisStatus: "Analysis",
      progress: "Checks",
    },
    empty: "No scans yet.",
    analysisPending: "—",
  },
  topics: {
    title: "Topics",
    subtitle: "Per-topic visibility metrics for this scan.",
    backToResults: "Back to scan results",
    viewTopics: "View topics",
    table: {
      headers: {
        topic: "Topic",
        mentionRate: "Mention rate",
        recommendationRate: "Rec. rate",
        shareOfVoice: "Share of voice",
        avgRank: "Avg rank",
        citations: "Citations",
        ownedShare: "Owned share",
        sentiment: "Sentiment",
      },
      empty: "No topic metrics available for this scan yet.",
      noData: "—",
    },
    detail: {
      backToTopics: "Back to topics",
      sections: {
        metrics: "Topic metrics",
        byPlatform: "By platform",
        topCited: "Top cited sources",
      },
      noPlatformData: "No per-platform answers landed in this topic.",
      noCitedSources: "No sources were cited within this topic.",
      tableHeaders: {
        platform: "Platform",
        answers: "Answers",
        mentionRate: "Mention rate",
        recommendationRate: "Rec. rate",
        shareOfVoice: "Share of voice",
        citations: "Citations",
        source: "Source",
        sourceCitations: "Citations",
      },
    },
    empty: {
      notFound: "Topic data not found for this scan.",
    },
  },
  sources: {
    title: "Sources",
    subtitle: "Every source cited in this scan, with classification and citation count.",
    backToResults: "Back to scan results",
    viewSources: "View sources",
    table: {
      headers: {
        source: "Source",
        type: "Type",
        provenance: "Classified by",
        citations: "Citations",
        platforms: "Platforms",
        action: "Open",
      },
      empty: "No sources were cited in this scan.",
    },
    provenance: {
      rule: "Rule-based",
      llm: "LLM",
      user: "You",
      tooltip: "Confidence: {confidence}",
    },
    drawer: {
      title: "Source citations",
      close: "Close",
      prompt: "Prompt",
      answerSnippet: "Answer snippet",
      openUrl: "Open URL",
      empty: "This source has no citations in this scan.",
      error: "Couldn't load citations.",
    },
    empty: {
      notFound: "Scan not found or analysis hasn't completed yet.",
    },
  },
} as const;
