/**
 * Placeholder body for chart-card info tooltips while the copy is being
 * authored. Lives in this file (not the component) so swapping it for the
 * real per-card text — eventually per-locale — is a content change, not a
 * code change. Remove this constant once every `tooltip` entry has bespoke
 * copy.
 */
const TBD_TOOLTIP = "Description coming soon.";

export const REPORTS_COPY = {
  scanResults: {
    title: "Scan Results",
    subtitle: "{brandName} — {trackerName}",
    sections: {
      summary: "Summary",
      coreMetrics: "Core Metrics",
      sentimentDistribution: "Brand Sentiment Distribution",
      topCitedSources: "Top Cited Sources",
      shareOfVoice: "Share of Voice",
      byPlatform: "By Platform",
      byLens: "By Visibility Lens",
      byTopic: "By Topic",
      byCompetitor: "By Competitor",
    },
    summary: {
      scanStatus: "Scan status",
      analysisStatus: "Analysis status",
      startedAt: "Started",
      completedAt: "Completed",
      checks: "{completed} of {total} checks completed",
      checksWithFailures: "{completed} of {total} checks ({failed} failed)",
      platforms: "Platforms",
    },
    metrics: {
      brandMentionRate: "Brand mention rate",
      brandRecommendationRate: "Recommendation rate",
      brandShareOfVoice: "Share of voice",
      averageBrandRank: "Average brand rank",
      competitorMentionCount: "Competitor mentions",
      productMentionCount: "Product mentions",
      citationCount: "Citations",
      ownedCitationCount: "Owned",
      competitorCitationCount: "Competitor",
      thirdPartyCitationCount: "Third-party",
      unknownCitationCount: "Unknown",
      ownedCitationShare: "Owned citation share",
      overallSentiment: "Overall sentiment",
      noData: "No data",
    },
    shareOfVoice: {
      title: "Share of voice — brand vs competitors",
      empty: "No brand or competitor mentions in this scan.",
      valueAxis: "Share",
    },
    breakdowns: {
      name: "Name",
      mentionRate: "Mention rate",
      recommendationRate: "Rec. rate",
      shareOfVoice: "SoV",
      citations: "Citations",
      mentionCount: "Mentions",
      recommendationCount: "Recommended",
      noRows: "No data for this dimension yet.",
    },
    empty: {
      notFound:
        "Scan results not found. The scan may not exist or analysis may not have started yet.",
    },
    error: {
      title: "Couldn't load scan results",
      description: "Something went wrong fetching the scan results.",
    },
  },
  dashboard: {
    title: "Visibility Tracker Dashboard",
    subtitle: "Trend over the past {days} days.",
    hero: {
      queries: "Queries",
      mentions: "Mentions",
      citations: "Citations",
      brandMentionRate: "Brand mention rate",
      noData: "—",
    },
    trend: {
      title: "Visibility over time",
      metricLabel: "Metric:",
      noData: "No trend data in the selected window yet.",
    },
    topBrands: {
      title: "Top brands",
      columns: {
        brand: "Brand",
        visibility: "Visibility",
        shareOfVoice: "SOV",
        sentiment: "Sentiment",
      },
      youChip: "You",
      noData: "—",
      empty: "No brands or competitors with data in this window.",
    },
    filter: {
      ariaLabel: "Window",
      day7: "7d",
      day30: "30d",
      day90: "90d",
    },
    empty: {
      notFound: "Tracker not found.",
      noScans: "No scans have run for this tracker yet.",
      noTrendData: "No trend data in the selected window yet.",
    },
    sov: {
      title: "Share of voice",
      noData: "No brand or competitor mentions in this window.",
    },
    mentions: {
      brandVsCompetitor: "Brand vs competitor mentions",
      distribution: "Mention distribution",
      axisLabel: "Mentions",
      noData: "No mention data in this window.",
    },
    competitiveGap: {
      title: "Competitive gap (brand vs each competitor)",
      mentionsAxis: "Mentions gap",
      recsAxis: "Recommendations gap",
      noData: "No tracked competitors mentioned in this window.",
    },
    recommendationRate: {
      title: "Recommendation rate by entity",
      axisLabel: "Rec. rate",
      noData: "No mentions in this window.",
    },
    topDomains: {
      title: "Top citation domains",
      columns: {
        source: "Source",
        domain: "Domain",
        type: "Type",
        citations: "Citations",
      },
      noData: "No citations in this window.",
    },
    domainTypes: {
      title: "Domain types",
      noData: "No citation data in this window.",
    },
    platforms: {
      title: "Mentions by platform",
      axisLabel: "Brand mention rate",
      noData: "No platform data in this window.",
    },
    sentiment: {
      title: "Brand sentiment distribution",
      noData: "No brand mentions in this window.",
    },
    activity: {
      title: "Activity heatmap",
      subtitle: "Brand mentions per scan, per platform",
      noData: "No scans in this window.",
    },
    topicCoverage: {
      title: "Topic coverage",
      subtitle: "Answers tagged with each topic, per platform",
      noData: "No topic data in this window.",
    },
    recentChats: {
      title: "Recent chats",
      empty: "No answers in this window.",
      mentionsLabel: "mentions",
      citationsLabel: "citations",
      noSentiment: "—",
      drawer: {
        title: "Answer detail",
        close: "Close",
        prompt: "Prompt",
        answer: "Answer",
        platform: "Platform",
        lens: "Visibility lens",
        captured: "Captured",
      },
    },
  },
  overview: {
    title: "Workspace Overview",
    subtitle: "Across all your tracked brands.",
    error: {
      title: "Couldn't load the overview",
      description: "Something went wrong fetching the workspace overview.",
    },
    empty: {
      noBrands: "You don't have any tracked brands yet. Add one to get started.",
      noScans: "No scans have run yet for any of your brands.",
      noTrendData: "No trend data in the selected window yet.",
    },
    trendChart: {
      tooltip: TBD_TOOLTIP,
    },
    topEntities: {
      title: "Top brands",
      tooltip: TBD_TOOLTIP,
      columns: {
        entity: "Brand",
        visibility: "Visibility",
        shareOfVoice: "SOV",
        sentiment: "Sentiment",
      },
      youChip: "You",
      noData: "—",
      empty: "No brands or competitors with data in this window.",
    },
    sov: {
      title: "Share of voice",
      tooltip: TBD_TOOLTIP,
      noData: "No brand or competitor mentions in this window.",
    },
    mentions: {
      brandVsCompetitor: "Brand vs competitor mentions",
      distribution: "Mention distribution",
      tooltip: TBD_TOOLTIP,
      axisLabel: "Mentions",
      noData: "No mention data in this window.",
    },
    competitiveGap: {
      title: "Competitive gap",
      tooltip: TBD_TOOLTIP,
      perBrandLabel: "Gaps for {brandName}",
      noData: "No tracked competitors mentioned in this window.",
      noGroups: "No tracked-brand gap data in this window.",
    },
    recommendationRate: {
      title: "Recommendation rate by entity",
      tooltip: TBD_TOOLTIP,
      axisLabel: "Rec. rate",
      noData: "No mentions in this window.",
    },
    topDomains: {
      title: "Top citation domains",
      tooltip: TBD_TOOLTIP,
      columns: {
        source: "Source",
        domain: "Domain",
        type: "Type",
        citations: "Citations",
      },
      noData: "No citations in this window.",
    },
    domainTypes: {
      title: "Domain types",
      tooltip: TBD_TOOLTIP,
      noData: "No citation data in this window.",
    },
    platforms: {
      title: "Mentions by platform",
      tooltip: TBD_TOOLTIP,
      axisLabel: "Brand mention rate",
      noData: "No platform data in this window.",
    },
    sentiment: {
      title: "Brand sentiment distribution",
      tooltip: TBD_TOOLTIP,
      noData: "No brand mentions in this window.",
    },
    topicCoverage: {
      title: "Topic coverage",
      tooltip: TBD_TOOLTIP,
      subtitle: "Per-topic coverage by platform — toggle to see answers or citations",
      noData: "No topic data in this window.",
      metricLabels: {
        aria: "Topic metric",
        answers: "Answers",
        citations: "Citations",
      },
    },
    recentChats: {
      title: "Recent chats",
      tooltip: TBD_TOOLTIP,
      empty: "No answers in this window.",
      mentionsLabel: "mentions",
      citationsLabel: "citations",
      drawer: {
        title: "Answer detail",
        close: "Close",
        prompt: "Prompt",
        answer: "Answer",
        platform: "Platform",
        lens: "Visibility lens",
        brand: "Brand",
        captured: "Captured",
      },
    },
  },
  trackerList: {
    title: "Trackers",
    subtitle: "Every configured visibility tracker. Analytics live on the Overview page.",
    columns: {
      name: "Tracker",
      brand: "Brand",
      status: "Status",
      scans: "Scans",
      latestScan: "Latest scan",
      created: "Created",
      actions: "",
    },
    empty: "No trackers configured yet.",
    never: "—",
    runNow: {
      button: "Run now",
      running: "Starting…",
      started: "Scan started.",
      failed: "Couldn't start the scan.",
      notRunnable: "—",
    },
  },
  scanList: {
    title: "All Scans",
    subtitle:
      "Temporary index of recent scans across all trackers. Click a row to open its results.",
    columns: {
      startedAt: "Started",
      brand: "Brand",
      tracker: "Tracker",
      scanStatus: "Scan",
      analysisStatus: "Analysis",
      progress: "Checks",
    },
    empty: "No scans yet.",
    analysisPending: "—",
  },
  competitors: {
    title: "Competitors",
    subtitle: "How often each tracked competitor was mentioned and recommended in this scan.",
    backToResults: "Back to scan results",
    viewCompetitors: "View competitors",
    table: {
      headers: {
        competitor: "Competitor",
        mentions: "Mentions",
        mentionRate: "Mention rate",
        recommendations: "Recommendations",
        recommendationRate: "Rec. rate",
      },
      empty: "No competitor metrics available for this scan.",
      noData: "—",
    },
    detail: {
      backToCompetitors: "Back to competitors",
      sections: {
        metrics: "Competitor metrics",
        sources: "Sources cited alongside this competitor",
      },
      noSources: "No sources were cited on answers that mentioned this competitor.",
      tableHeaders: {
        source: "Source",
        domain: "Domain",
        citations: "Citations",
      },
    },
    empty: {
      notFound: "Competitor data not found for this scan.",
    },
  },
  topics: {
    title: "Topics",
    subtitle: "Per-topic visibility metrics for this scan.",
    backToResults: "Back to scan results",
    viewTopics: "View topics",
    table: {
      headers: {
        topic: "Topic",
        ownership: "Ownership",
        mentionRate: "Mention rate",
        recommendationRate: "Rec. rate",
        shareOfVoice: "Share of voice",
        avgRank: "Avg rank",
        citations: "Citations",
        ownedShare: "Owned share",
        sentiment: "Sentiment",
      },
      ownership: {
        Owned: "Owned",
        Contested: "Contested",
        Lost: "Lost",
      } as Record<string, string>,
      empty: "No topic metrics available for this scan yet.",
      noData: "—",
    },
    detail: {
      backToTopics: "Back to topics",
      sections: {
        metrics: "Topic metrics",
        byPlatform: "By platform",
        topCited: "Top cited sources",
      },
      noPlatformData: "No per-platform answers landed in this topic.",
      noCitedSources: "No sources were cited within this topic.",
      tableHeaders: {
        platform: "Platform",
        answers: "Answers",
        mentionRate: "Mention rate",
        recommendationRate: "Rec. rate",
        shareOfVoice: "Share of voice",
        citations: "Citations",
        source: "Source",
        sourceCitations: "Citations",
      },
    },
    empty: {
      notFound: "Topic data not found for this scan.",
    },
  },
  sources: {
    title: "Sources",
    subtitle: "Every source cited in this scan, with classification and citation count.",
    backToResults: "Back to scan results",
    viewSources: "View sources",
    table: {
      headers: {
        source: "Source",
        type: "Type",
        provenance: "Classified by",
        citations: "Citations",
        platforms: "Platforms",
        action: "Open",
      },
      empty: "No sources were cited in this scan.",
    },
    provenance: {
      rule: "Rule-based",
      llm: "LLM",
      user: "You",
      tooltip: "Confidence: {confidence}",
    },
    drawer: {
      title: "Source citations",
      close: "Close",
      prompt: "Prompt",
      answerSnippet: "Answer snippet",
      openUrl: "Open URL",
      empty: "This source has no citations in this scan.",
      error: "Couldn't load citations.",
    },
    empty: {
      notFound: "Scan not found or analysis hasn't completed yet.",
    },
  },
} as const;
