export const TRACKERS_COPY = {
  ready: {
    title: "Ready to create your Visibility Tracker",
    description:
      "We'll monitor how AI platforms talk about {brandName} using your confirmed discovery.",
    nameLabel: "Tracker name",
    coverageTitle: "What this tracker will monitor",
    create: "Create Visibility Tracker",
    creating: "Creating...",
    summary: {
      topics: "Topics",
      competitors: "Competitors",
      products: "Products & Services",
      audiences: "Audiences",
      markets: "Markets",
      visibilityChecks: "Visibility Checks",
    },
  },
  created: {
    title: "Visibility Tracker created",
    description: "{name} is ready. Prompt setup is coming next.",
  },
  review: {
    title: "Review your prompts",
    description:
      "These prompts will run across AI platforms. Remove any that don't fit, regenerate, or confirm to continue.",
    generating: "Generating your prompts...",
    allocation: "{count} / {allocation} prompts",
    regenerate: "Regenerate all",
    regenerateCheck: "Regenerate {check}",
    collapse: "Collapse {check}",
    expand: "Expand {check}",
    sourceAi: "AI-generated",
    sourceHuman: "Added by you",
    editPlaceholder: "Edit prompt",
    needsReview: "Review",
    checkDescriptions: {
      Discovery: "Does AI surface your brand for category and topic questions?",
      "Buying Intent": "Is your brand recommended for purchase-ready prompts?",
      "Competitor Comparison": "How AI weighs your brand against competitors.",
      "Sentiment & Trust": "The sentiment and trust AI expresses about your brand.",
      "Citation Visibility": "Is your content cited as a source in AI answers?",
      "Content Gaps": "Where your brand is missing but should appear.",
    },
    confirm: "Confirm prompts",
    confirming: "Confirming...",
    empty: "No prompts yet.",
    generate: "Generate prompts",
    custom: "Custom",
    addCustom: "Add custom prompt",
    addPlaceholder: "Type a prompt...",
    checkPlaceholder: "Visibility check",
    topicPlaceholder: "Topic (optional)",
    add: "Add",
    cancel: "Cancel",
    regeneratePlaceholder: "Regenerate...",
    scopeAll: "All prompts",
    byCheckLabel: "Check",
    byTopicLabel: "Topic",
    remaining: "{remaining} left",
    full: "Tracker is full — remove a prompt to add another.",
    confirmedTitle: "Prompts confirmed",
    confirmedDescription:
      "{count} prompts are active. Platform & cadence selection is coming next.",
  },
} as const;
