export const TRACKERS_COPY = {
  ready: {
    title: "Ready to create your Visibility Tracker",
    description:
      "We'll monitor how AI platforms talk about {brandName} using your confirmed discovery.",
    nameLabel: "Tracker name",
    coverageTitle: "What this tracker will monitor",
    create: "Create Visibility Tracker",
    creating: "Creating...",
    summary: {
      topics: "Topics",
      competitors: "Competitors",
      products: "Products & Services",
      audiences: "Audiences",
      markets: "Markets",
      lenses: "Visibility Lenses",
    },
  },
  created: {
    title: "Visibility Tracker created",
    description: "{name} is ready. Prompt setup is coming next.",
  },
  review: {
    title: "Review your prompts",
    description:
      "These prompts will run across AI platforms. Remove any that don't fit, regenerate, or confirm to continue.",
    generating: "Generating your prompts...",
    allocation: "{count} / {allocation} prompts",
    regenerate: "Regenerate all",
    regenerateCheck: "Regenerate {check}",
    collapse: "Collapse {check}",
    expand: "Expand {check}",
    sourceAi: "AI-generated",
    sourceHuman: "Added by you",
    editPlaceholder: "Edit prompt",
    needsReview: "Review",
    confidenceHigh: "High",
    checkDescriptions: {
      Discovery: "Does AI surface your brand for category and topic questions?",
      "Buying Intent": "Is your brand recommended for purchase-ready prompts?",
      "Competitor Comparison": "How AI weighs your brand against competitors.",
      "Sentiment & Trust": "The sentiment and trust AI expresses about your brand.",
      "Citation Visibility": "Is your content cited as a source in AI answers?",
      "Content Gaps": "Where your brand is missing but should appear.",
    },
    confirm: "Confirm prompts",
    confirming: "Confirming...",
    empty: "No prompts yet.",
    generate: "Generate prompts",
    custom: "Custom",
    addCustom: "Add custom prompt",
    addPlaceholder: "Type a prompt...",
    checkPlaceholder: "Visibility lens",
    topicPlaceholder: "Topic (optional)",
    add: "Add",
    cancel: "Cancel",
    regeneratePlaceholder: "Regenerate...",
    scopeAll: "All prompts",
    byCheckLabel: "Lens",
    byTopicLabel: "Topic",
    remaining: "{remaining} left",
    full: "Tracker is full — remove a prompt to add another.",
    confirmedTitle: "Prompts confirmed",
    confirmedDescription:
      "{count} prompts are active. Platform & cadence selection is coming next.",
  },
  schedule: {
    title: "Set up scanning",
    description: "Choose which AI platforms to scan {brandName} on, and how often.",
    platformsLabel: "AI platforms",
    cadenceLabel: "Cadence",
    timezoneLabel: "Time zone",
    platformNeedsKey: "Needs API key",
    cadence: {
      OnDemand: "On demand",
      Daily: "Daily",
      Weekly: "Weekly",
    },
    estimate: "{prompts} prompts × {platforms} platforms = {checks} scan checks",
    noPlatforms: "Select at least one platform.",
    activate: "Activate tracker",
    activating: "Activating...",
    activatedTitle: "Tracker is active",
    activatedDescription: "{checks} scan checks, {cadence} cadence.",
  },
  scan: {
    // Live progress screen (post-activation, while the scan runs).
    progressTitleTemplate: "Checking {platforms} for {brand}…",
    progressTitleFallback: "Checking AI platforms for {brand}…",
    progressSubtext: "{done}/{total} complete",
    platformStatus: {
      Pending: "Pending",
      Running: "Running",
      Done: "Done",
      Failed: "Failed",
    } as Record<string, string>,
    liveResultsTitle: "Live results",
    mentions: "Mentions",
    citations: "Citations",
    recommended: "Recommended",
    sentiment: "Sentiment",
    // Product-awareness messages that cycle every ~6s in place of the
    // old McKinsey pull-quote. Order is the rotation order; keep them
    // self-contained sentences so the rotation reads naturally.
    awarenessMessages: [
      "Visibility Lenses look at your brand through 6 angles — Discovery, Buying Intent, Competitor Comparison, Sentiment & Trust, Citation Visibility, and Content Gaps.",
      "A Tracker is a long-lived view of how AI platforms talk about your brand. Every scan adds another snapshot to the trend.",
      "The thorough discovery you just did means every future scan asks better questions. The work is already paying off.",
      "We analyze every answer the way a careful reviewer would — sentence by sentence, source by source — just faster.",
      "Trends move the needle. One scan tells you where you stand; the next tells you whether you're getting better.",
      "Citations show you which sources AI reaches for in your category — and whether your own content is in the mix.",
    ] as readonly string[],
    // Complete screen (terminal state after Completed / Failed).
    completeTitle: "Your first scan is complete!",
    completeSubtitle:
      "We've analyzed how AI platforms talk about {brand} across {queries} queries.",
    completeSubtitleFallback:
      "We've analyzed how AI platforms talk about your brand across {queries} queries.",
    whatWeFoundTitle: "What we found",
    completeBody:
      "This is just the beginning. Your scan results have detailed insights, trends, and recommendations.",
    viewScanResults: "View scan results",
    sentimentLabels: {
      Positive: "Positive",
      Neutral: "Neutral",
      Negative: "Negative",
      Mixed: "Mixed",
      Unknown: "Pending",
    } as Record<string, string>,
  },
} as const;
